server {
    listen 8080;
    server_name localhost;
    charset utf-8;

    location /kindle/ {
        alias /usr/share/nginx/kindle/;
        index index.html;
    }

    location / {
        proxy_pass http://reader:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
